-- shift_cellsテーブルの作成（シフト表のセルデータを保存）
CREATE TABLE IF NOT EXISTS public.shift_cells (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL,
  date DATE NOT NULL,
  shift_code TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
  
  -- ユニーク制約（従業員と日付の組み合わせは一意）
  CONSTRAINT shift_cells_employee_date_unique UNIQUE (employee_id, date)
);

-- RLSポリシーの設定
ALTER TABLE public.shift_cells ENABLE ROW LEVEL SECURITY;
CREATE POLICY "全ユーザーがシフトデータにアクセス可能" ON public.shift_cells
  FOR ALL TO PUBLIC USING (true);

-- インデックスの作成
CREATE INDEX IF NOT EXISTS shift_cells_employee_id_idx ON public.shift_cells (employee_id);
CREATE INDEX IF NOT EXISTS shift_cells_date_idx ON public.shift_cells (date);

COMMENT ON TABLE public.shift_cells IS 'シフト表のセルデータを保存するテーブル';
