import './globals.css';
import type { Metadata } from 'next';
import { ShiftTypesProvider } from '@/contexts/shift-types-context';
import { Toaster } from '@/components/ui/toaster';
import { Toaster as SonnerToaster } from 'sonner';
import { Inter } from 'next/font/google';

// フォントの設定
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={inter.className}>
      <body className="font-sans">
        <ShiftTypesProvider>
          {children}
          <Toaster />
          <SonnerToaster position="top-right" />
        </ShiftTypesProvider>
      </body>
    </html>
  );
}